import { Event, EventCategory, EventHost } from './types';
import { CURRENT_USER_ID } from './mock-data';

// Mock event hosts
export const MOCK_HOSTS: EventHost[] = [
  {
    user_id: 'host-1',
    display_name: 'Maya & James',
    photo: 'https://images.unsplash.com/photo-1522673607200-164d1b6ce486?w=200',
    reputation_stars: 4,
    events_hosted: 12,
  },
  {
    user_id: 'host-2',
    display_name: 'Luna',
    photo: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200',
    reputation_stars: 5,
    events_hosted: 28,
  },
  {
    user_id: 'host-3',
    display_name: 'The Poly Collective',
    photo: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=200',
    reputation_stars: 5,
    events_hosted: 45,
  },
  {
    user_id: CURRENT_USER_ID,
    display_name: 'You',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200',
    reputation_stars: 3,
    events_hosted: 2,
  },
];

// Event category metadata
export const EVENT_CATEGORIES: { id: EventCategory; label: string; emoji: string; color: string }[] = [
  { id: 'social', label: 'Social', emoji: '🎉', color: '#f472b6' },
  { id: 'dating', label: 'Dating', emoji: '💕', color: '#f87171' },
  { id: 'education', label: 'Education', emoji: '📚', color: '#60a5fa' },
  { id: 'party', label: 'Party', emoji: '🎊', color: '#c084fc' },
  { id: 'outdoor', label: 'Outdoor', emoji: '🌳', color: '#4ade80' },
  { id: 'wellness', label: 'Wellness', emoji: '🧘', color: '#2dd4bf' },
  { id: 'meetup', label: 'Meetup', emoji: '👋', color: '#fbbf24' },
  { id: 'virtual', label: 'Virtual', emoji: '💻', color: '#818cf8' },
  { id: 'private', label: 'Private', emoji: '🔒', color: '#94a3b8' },
  { id: 'community', label: 'Community', emoji: '🤝', color: '#fb923c' },
];

// Popular event tags
export const EVENT_TAGS = [
  'poly-friendly',
  'couples-welcome',
  'singles',
  'lgbtq+',
  'kink-aware',
  'newbie-friendly',
  'discussion',
  'social-mixer',
  'speed-dating',
  'workshop',
  'support-group',
  'game-night',
  'book-club',
  'hiking',
  'dinner-party',
  'brunch',
  'dance',
  'meditation',
  'yoga',
  'art',
];

// Helper to get future dates
const getFutureDate = (daysFromNow: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString().split('T')[0];
};

// Mock events
export const MOCK_EVENTS: Event[] = [
  {
    id: 'event-1',
    host_id: 'host-2',
    host: MOCK_HOSTS[1]!,
    title: 'Poly Potluck & Game Night',
    description:
      "Join us for a cozy evening of good food, board games, and great conversation! Bring a dish to share and your favorite game. This is a casual, low-key event perfect for meeting new people in the community.\n\nWe'll have tables set up for various games, from classics like Settlers of Catan to party games like Codenames. Whether you're new to polyamory or a seasoned pro, everyone is welcome!",
    cover_image: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=800',
    category: 'social',
    tags: ['poly-friendly', 'game-night', 'newbie-friendly', 'dinner-party'],
    location: {
      name: "Luna's Place",
      address: '456 Oak Street, Apt 3B',
      city: 'San Francisco',
      latitude: 37.7749,
      longitude: -122.4194,
    },
    start_date: getFutureDate(3),
    start_time: '18:00',
    end_time: '22:00',
    timezone: 'America/Los_Angeles',
    max_attendees: 20,
    current_attendees: 14,
    waitlist_count: 2,
    visibility: 'public',
    requires_approval: false,
    status: 'published',
    is_featured: true,
    is_recurring: true,
    recurring_pattern: 'monthly',
    attendees: [],
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'event-2',
    host_id: 'host-3',
    host: MOCK_HOSTS[2]!,
    title: 'ENM 101: Intro to Ethical Non-Monogamy',
    description:
      "Curious about ethical non-monogamy? Whether you're just starting to explore or looking to deepen your understanding, this workshop covers the fundamentals.\n\nTopics include:\n- Different relationship structures (polyamory, open relationships, relationship anarchy)\n- Communication frameworks\n- Managing jealousy\n- Setting healthy boundaries\n- Resources for continued learning\n\nLed by experienced facilitators with 10+ years in the ENM community.",
    cover_image: 'https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800',
    category: 'education',
    tags: ['workshop', 'newbie-friendly', 'discussion', 'poly-friendly'],
    location: {
      name: 'Community Center',
      address: '789 Community Way',
      city: 'San Francisco',
      latitude: 37.7849,
      longitude: -122.4094,
    },
    start_date: getFutureDate(7),
    start_time: '14:00',
    end_time: '17:00',
    timezone: 'America/Los_Angeles',
    max_attendees: 30,
    current_attendees: 22,
    waitlist_count: 0,
    visibility: 'public',
    requires_approval: false,
    status: 'published',
    is_featured: true,
    is_recurring: false,
    attendees: [],
    created_at: '2024-01-14T10:00:00Z',
    updated_at: '2024-01-14T10:00:00Z',
  },
  {
    id: 'event-3',
    host_id: 'host-1',
    host: MOCK_HOSTS[0]!,
    title: 'Couples + Singles Mixer',
    description:
      "A relaxed evening for couples looking to meet singles and singles interested in joining established relationships. We'll have icebreaker activities, speed-meeting rounds, and plenty of time for organic mingling.\n\nDrinks and light appetizers provided. 21+ only.",
    cover_image: 'https://images.unsplash.com/photo-1543807535-eceef0bc6599?w=800',
    category: 'dating',
    tags: ['couples-welcome', 'singles', 'social-mixer', 'speed-dating'],
    location: {
      name: 'The Velvet Lounge',
      address: '123 Main Street',
      city: 'Oakland',
      latitude: 37.8044,
      longitude: -122.2712,
    },
    start_date: getFutureDate(5),
    start_time: '20:00',
    end_time: '23:00',
    timezone: 'America/Los_Angeles',
    max_attendees: 40,
    current_attendees: 28,
    waitlist_count: 5,
    visibility: 'public',
    requires_approval: false,
    status: 'published',
    is_featured: false,
    is_recurring: false,
    attendees: [],
    created_at: '2024-01-13T10:00:00Z',
    updated_at: '2024-01-13T10:00:00Z',
  },
  {
    id: 'event-4',
    host_id: 'host-2',
    host: MOCK_HOSTS[1]!,
    title: 'Morning Hike & Coffee',
    description:
      "Start your Saturday with nature and good company! We'll do a moderate 5-mile hike followed by coffee at a nearby café.\n\nAll fitness levels welcome - we go at a relaxed pace with plenty of stops for photos and conversation. Great opportunity to connect with fellow ENM folks in a casual, active setting.",
    cover_image: 'https://images.unsplash.com/photo-1551632811-561732d1e306?w=800',
    category: 'outdoor',
    tags: ['hiking', 'poly-friendly', 'lgbtq+'],
    location: {
      name: 'Tilden Regional Park',
      address: 'Grizzly Peak Blvd',
      city: 'Berkeley',
      latitude: 37.9057,
      longitude: -122.2439,
    },
    start_date: getFutureDate(2),
    start_time: '08:00',
    end_time: '12:00',
    timezone: 'America/Los_Angeles',
    max_attendees: 15,
    current_attendees: 8,
    waitlist_count: 0,
    visibility: 'public',
    requires_approval: false,
    status: 'published',
    is_featured: false,
    is_recurring: true,
    recurring_pattern: 'weekly',
    attendees: [],
    created_at: '2024-01-12T10:00:00Z',
    updated_at: '2024-01-12T10:00:00Z',
  },
  {
    id: 'event-5',
    host_id: 'host-3',
    host: MOCK_HOSTS[2]!,
    title: 'Virtual: Jealousy Workshop',
    description:
      "Jealousy is natural - but it doesn't have to control you. Join this virtual workshop to explore healthy ways to understand, communicate about, and transform jealousy into compersion.\n\nWe'll cover:\n- Understanding the root causes of jealousy\n- Communication techniques for difficult conversations\n- Practical exercises for self-soothing\n- Building security in multiple relationships",
    cover_image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800',
    category: 'virtual',
    tags: ['workshop', 'discussion', 'poly-friendly'],
    location: {
      name: 'Zoom Meeting',
      address: 'Online',
      city: 'Virtual',
      latitude: 0,
      longitude: 0,
      is_virtual: true,
      virtual_link: 'https://zoom.us/j/123456789',
    },
    start_date: getFutureDate(10),
    start_time: '19:00',
    end_time: '21:00',
    timezone: 'America/Los_Angeles',
    max_attendees: 50,
    current_attendees: 32,
    waitlist_count: 0,
    visibility: 'public',
    requires_approval: false,
    status: 'published',
    is_featured: true,
    is_recurring: false,
    attendees: [],
    created_at: '2024-01-11T10:00:00Z',
    updated_at: '2024-01-11T10:00:00Z',
  },
  {
    id: 'event-6',
    host_id: 'host-1',
    host: MOCK_HOSTS[0]!,
    title: 'Private: Intimate Dinner Party',
    description:
      "An exclusive dinner party for verified couples and experienced community members. Fine dining, great wine, and deep conversations in an intimate setting.\n\nThis is an invite-only event - please request access and we'll review your profile.",
    cover_image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800',
    category: 'private',
    tags: ['couples-welcome', 'dinner-party', 'kink-aware'],
    location: {
      name: 'Private Residence',
      address: 'Address shared upon approval',
      city: 'San Francisco',
      latitude: 37.7749,
      longitude: -122.4194,
    },
    start_date: getFutureDate(14),
    start_time: '19:00',
    end_time: '23:00',
    timezone: 'America/Los_Angeles',
    max_attendees: 12,
    current_attendees: 8,
    waitlist_count: 4,
    visibility: 'invite_only',
    requires_approval: true,
    status: 'published',
    is_featured: false,
    is_recurring: false,
    attendees: [],
    created_at: '2024-01-10T10:00:00Z',
    updated_at: '2024-01-10T10:00:00Z',
  },
  {
    id: 'event-7',
    host_id: 'host-2',
    host: MOCK_HOSTS[1]!,
    title: 'Poly Book Club: Polysecure',
    description:
      "This month we're reading 'Polysecure' by Jessica Fern. Join us to discuss attachment theory, trauma-informed approaches to non-monogamy, and building secure relationships.\n\nEven if you haven't finished the book, come share your thoughts on what you've read so far!",
    cover_image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=800',
    category: 'community',
    tags: ['book-club', 'discussion', 'poly-friendly', 'newbie-friendly'],
    location: {
      name: 'Borderlands Books',
      address: '866 Valencia St',
      city: 'San Francisco',
      latitude: 37.7589,
      longitude: -122.4214,
    },
    start_date: getFutureDate(8),
    start_time: '18:30',
    end_time: '20:30',
    timezone: 'America/Los_Angeles',
    max_attendees: 25,
    current_attendees: 18,
    waitlist_count: 0,
    visibility: 'public',
    requires_approval: false,
    status: 'published',
    is_featured: false,
    is_recurring: true,
    recurring_pattern: 'monthly',
    attendees: [],
    created_at: '2024-01-09T10:00:00Z',
    updated_at: '2024-01-09T10:00:00Z',
  },
  {
    id: 'event-8',
    host_id: 'host-3',
    host: MOCK_HOSTS[2]!,
    title: 'Relationship Anarchy Brunch',
    description:
      "Calling all relationship anarchists and RA-curious folks! Join us for brunch and conversation about building authentic connections free from societal scripts.\n\nWe'll discuss relationship autonomy, consent culture, and creating your own relationship rules (or lack thereof).",
    cover_image: 'https://images.unsplash.com/photo-1504754524776-8f4f37790ca0?w=800',
    category: 'social',
    tags: ['brunch', 'discussion', 'lgbtq+', 'poly-friendly'],
    location: {
      name: 'The Garden Café',
      address: '2101 Shattuck Ave',
      city: 'Berkeley',
      latitude: 37.8716,
      longitude: -122.2727,
    },
    start_date: getFutureDate(4),
    start_time: '11:00',
    end_time: '14:00',
    timezone: 'America/Los_Angeles',
    max_attendees: 16,
    current_attendees: 12,
    waitlist_count: 0,
    visibility: 'public',
    requires_approval: false,
    status: 'published',
    is_featured: false,
    is_recurring: false,
    attendees: [],
    created_at: '2024-01-08T10:00:00Z',
    updated_at: '2024-01-08T10:00:00Z',
  },
];

// Helper function to get featured events
export const getFeaturedEvents = (): Event[] => {
  return MOCK_EVENTS.filter((e) => e.is_featured && e.status === 'published');
};

// Helper function to get upcoming events sorted by date
export const getUpcomingEvents = (): Event[] => {
  return MOCK_EVENTS
    .filter((e) => e.status === 'published')
    .sort((a, b) => new Date(a.start_date).getTime() - new Date(b.start_date).getTime());
};

// Helper function to get events by category
export const getEventsByCategory = (category: EventCategory): Event[] => {
  return MOCK_EVENTS.filter((e) => e.category === category && e.status === 'published');
};
